/** @type {import("prettier").Config & import("@ianvs/prettier-plugin-sort-imports").PluginConfig} */
module.exports = {
    bracketSpacing: true,
    bracketSameLine: true,
    singleQuote: true,
    trailingComma: 'all',
    arrowParens: 'avoid',
    tabWidth: 4,
    printWidth: 100,
    quoteProps: 'consistent',
    plugins: ['@ianvs/prettier-plugin-sort-imports', 'prettier-plugin-tailwindcss'],
    tailwindFunctions: ['cn'],
    tailwindStylesheet: './src/styles/global.css',
    importOrder: [
        '^react$',
        '^next$',
        '<THIRD_PARTY_MODULES>',
        '',
        '^~/components/(.*)$',
        '^~/actions/(.*)$',
        '^~/hooks/(.*)$',
        '^~/utils/(.*)$',
        '^~/styles/(.*)$',
        '',
        '^~/app/(.*)$',
        '^~(.*)$',
        '',
        '^~/types/(.*)$',
        '^[./]',
    ],
    importOrderParserPlugins: ['typescript', 'jsx', 'decorators-legacy'],
    importOrderTypeScriptVersion: '5.0.0',
};
